import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader';
import { RGBELoader } from 'three/examples/jsm/loaders/RGBELoader';
import { EXRLoader } from 'three/examples/jsm/loaders/EXRLoader';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
import { CSS3DRenderer, CSS3DObject } from 'three/examples/jsm/renderers/CSS3DRenderer';
import Stats from 'three/examples/jsm/libs/stats.module';
import WebGPURenderer from 'three/examples/jsm/renderers/webgpu/WebGPURenderer';
import { WebGLRenderer } from 'three';
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
export { THREE, GLTFLoader, DRACOLoader, RGBELoader, EXRLoader, OrbitControls, CSS3DRenderer, CSS3DObject, Stats, WebGPURenderer, WebGLRenderer, type GLTF, };
export default THREE;
